### ISSUE TITLE
rust安装

### ISSUE THREAD

**Issue by wuyuedefeng** [wsblogs/rust#1]
### [官方](https://rustup.rs/)
```bash
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

```

### homebrew
```bash
brew install rust
```

## 更新和卸载
```bash
# 更新
$ rustup update
# 卸载
$ rustup self uninstall
# 查看版本
$ rustc --version
```

**Comment by wuyuedefeng** [comment]
### 字节国内镜像配置 
https://rsproxy.cn/
```toml
[source.crates-io]
# To use sparse index, change 'rsproxy' to 'rsproxy-sparse'
replace-with = 'rsproxy'

[source.rsproxy]
registry = "https://rsproxy.cn/crates.io-index"
[source.rsproxy-sparse]
registry = "sparse+https://rsproxy.cn/index/"

[registries.rsproxy]
index = "https://rsproxy.cn/crates.io-index"

[net]
git-fetch-with-cli = true

```
